// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using api.presentation.Data;

namespace presentation.Data.Migrations
{
    [DbContext(typeof(DataContext))]
    partial class DataContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "5.0.16");

            modelBuilder.Entity("api.presentation.Models.Product", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Description")
                        .HasColumnType("TEXT");

                    b.Property<string>("Image")
                        .HasColumnType("TEXT");

                    b.Property<float>("Price")
                        .HasColumnType("REAL");

                    b.Property<string>("Title")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Products");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Description = "Molestias dolor rerum ut. Dolor rerum pariatur fugit nemo quaerat. Quia aut et quo nemo dolor impedit fugit dolor. Et suscipit quis ipsam aut repellat dolores.",
                            Image = "http://lorempixel.com/640/480/transport",
                            Price = 46f,
                            Title = "velit"
                        },
                        new
                        {
                            Id = 2,
                            Description = "Sed natus ut rerum veritatis esse similique. Minima perferendis qui molestias est. Aperiam eveniet incidunt aut corrupti. Qui recusandae maxime est soluta. Architecto hic aliquid.",
                            Image = "http://lorempixel.com/640/480/animals",
                            Price = 92f,
                            Title = "unde"
                        },
                        new
                        {
                            Id = 3,
                            Description = "Assumenda ut ducimus libero porro exercitationem perspiciatis et exercitationem. Est omnis ut illum sapiente animi. Animi inventore adipisci ratione ut vel expedita a.",
                            Image = "http://lorempixel.com/640/480/transport",
                            Price = 40f,
                            Title = "impedit"
                        },
                        new
                        {
                            Id = 4,
                            Description = "Aut voluptatem ad repellat. Nobis qui error dicta consectetur temporibus delectus. Quia alias ut unde quaerat maiores facere velit. Est eaque harum quas provident. Impedit maxime a et iusto nesciunt enim qui et. Corporis ad ratione ipsum excepturi accusamus ea.",
                            Image = "http://lorempixel.com/640/480/business",
                            Price = 67f,
                            Title = "dolorum"
                        },
                        new
                        {
                            Id = 5,
                            Description = "Nihil beatae quidem. Est aut quis labore. Aut voluptatem distinctio at laboriosam. Et non voluptatum perferendis. In alias a impedit est labore.",
                            Image = "http://lorempixel.com/640/480/sports",
                            Price = 81f,
                            Title = "corrupti"
                        },
                        new
                        {
                            Id = 6,
                            Description = "Quae eos expedita voluptatem debitis quis adipisci iusto quas. Voluptatem dolor nostrum quia. Voluptatem ipsum harum sed et sequi. Labore et quam quia molestiae harum.",
                            Image = "http://lorempixel.com/640/480/nightlife",
                            Price = 11f,
                            Title = "harum"
                        },
                        new
                        {
                            Id = 7,
                            Description = "Qui odit cupiditate velit voluptatem ea culpa sit ipsa excepturi. Eos dolorem nam qui. Et dolorum ratione. Autem porro similique. Alias eveniet facere ea natus hic corrupti dolorum et voluptatem.",
                            Image = "http://lorempixel.com/640/480/animals",
                            Price = 11f,
                            Title = "deserunt"
                        },
                        new
                        {
                            Id = 8,
                            Description = "Enim a quia fugit. Aperiam excepturi mollitia blanditiis laboriosam excepturi error qui dignissimos excepturi. Nihil sed fuga.",
                            Image = "http://lorempixel.com/640/480/business",
                            Price = 21f,
                            Title = "sapiente"
                        },
                        new
                        {
                            Id = 9,
                            Description = "Sunt accusantium qui atque natus sint sunt nesciunt et. Debitis eos rem id est et. Corporis exercitationem sit ab eum sunt.",
                            Image = "http://lorempixel.com/640/480/business",
                            Price = 22f,
                            Title = "id"
                        },
                        new
                        {
                            Id = 10,
                            Description = "Laboriosam et doloremque nam id omnis. Itaque qui doloremque. Earum assumenda ex. Molestiae similique autem est illum non possimus impedit qui. Sed quisquam nihil recusandae voluptate.",
                            Image = "http://lorempixel.com/640/480/city",
                            Price = 48f,
                            Title = "qui"
                        },
                        new
                        {
                            Id = 11,
                            Description = "Aut odio non in et culpa libero esse praesentium. Ex magnam eligendi fuga dolorem. Voluptas quos et unde culpa non non.",
                            Image = "http://lorempixel.com/640/480/city",
                            Price = 58f,
                            Title = "temporibus"
                        },
                        new
                        {
                            Id = 12,
                            Description = "Quae nobis dolorum. Cum sed debitis corrupti. Aut est ut quaerat nisi. Iste tenetur tenetur accusantium vitae.",
                            Image = "http://lorempixel.com/640/480/nature",
                            Price = 82f,
                            Title = "eum"
                        },
                        new
                        {
                            Id = 13,
                            Description = "Perspiciatis labore tempore incidunt at et explicabo ut nam quis. Facilis quia sunt nesciunt maxime cum magnam temporibus assumenda. Quis labore a et ea culpa et ut. Dolore aut eligendi voluptatem. Exercitationem quia quaerat quas. Harum ut deserunt.",
                            Image = "http://lorempixel.com/640/480/transport",
                            Price = 53f,
                            Title = "culpa"
                        },
                        new
                        {
                            Id = 14,
                            Description = "Et laboriosam sunt unde temporibus nesciunt. Quaerat alias porro in. Veniam nostrum aperiam molestiae quia tempore. Earum odio et sed quam maxime nobis dolores cumque eligendi. Deleniti quod et sed itaque.",
                            Image = "http://lorempixel.com/640/480/technics",
                            Price = 23f,
                            Title = "repudiandae"
                        },
                        new
                        {
                            Id = 15,
                            Description = "Ab officiis exercitationem quos soluta illo qui. Itaque dolorem pariatur aut sapiente. Earum alias et libero aut aut voluptatem sint error. Ut fugiat quibusdam vitae ex eos minima molestiae.",
                            Image = "http://lorempixel.com/640/480/city",
                            Price = 47f,
                            Title = "optio"
                        },
                        new
                        {
                            Id = 16,
                            Description = "Quae quod est eos temporibus omnis non. Cum omnis pariatur quaerat recusandae explicabo. Saepe non excepturi sed enim iste. Nulla quaerat id doloribus et. Quam qui omnis repudiandae autem et facere non fugit et.",
                            Image = "http://lorempixel.com/640/480/cats",
                            Price = 78f,
                            Title = "saepe"
                        },
                        new
                        {
                            Id = 17,
                            Description = "Inventore rerum qui quam ipsa quibusdam sed. Eveniet ex aliquam perferendis. Saepe et quia et sapiente rerum asperiores tempora tempora. Rerum et laboriosam omnis omnis ut minima dolor ad ut.",
                            Image = "http://lorempixel.com/640/480/nature",
                            Price = 81f,
                            Title = "aperiam"
                        },
                        new
                        {
                            Id = 18,
                            Description = "Possimus sunt rerum nemo et iste sed. Sapiente aperiam nobis sed et autem. Voluptas sit fugiat aut itaque et. Et possimus quia dolorum in reiciendis dolor sunt. Quia quia incidunt. Omnis odit et sunt.",
                            Image = "http://lorempixel.com/640/480/city",
                            Price = 79f,
                            Title = "enim"
                        },
                        new
                        {
                            Id = 19,
                            Description = "Explicabo pariatur nulla doloribus rerum et consequatur. Ullam reiciendis est illo nulla consequuntur magni aperiam voluptatibus qui. Officiis non natus voluptates sed officia quo modi. Quaerat harum ipsum voluptas voluptas est.",
                            Image = "http://lorempixel.com/640/480/people",
                            Price = 39f,
                            Title = "beatae"
                        },
                        new
                        {
                            Id = 20,
                            Description = "Debitis quisquam ratione. Tempora qui voluptatem impedit voluptatibus temporibus ut qui fuga. Quas officia provident itaque facilis in. Soluta a optio. Consequatur aut est sed praesentium aut quaerat qui.",
                            Image = "http://lorempixel.com/640/480/abstract",
                            Price = 79f,
                            Title = "est"
                        },
                        new
                        {
                            Id = 21,
                            Description = "Nobis et iusto magni et dolorum porro ut. In qui eos dolores eum magni amet. Adipisci voluptas ducimus. Quam omnis molestiae officia. Voluptatibus minima alias in soluta ex aut. Aliquam accusantium delectus sint odio laboriosam voluptatibus et voluptatem.",
                            Image = "http://lorempixel.com/640/480/food",
                            Price = 92f,
                            Title = "voluptatem"
                        },
                        new
                        {
                            Id = 22,
                            Description = "Magni non repellat similique iure suscipit. Voluptatem voluptas aut ut quisquam quidem iusto. Ut porro totam suscipit. Magni odit modi dolores facere.",
                            Image = "http://lorempixel.com/640/480/food",
                            Price = 52f,
                            Title = "voluptatibus"
                        },
                        new
                        {
                            Id = 23,
                            Description = "Cupiditate est consectetur natus voluptatem. In fugit delectus totam eius doloribus amet tenetur autem. Cumque perspiciatis velit nostrum est iusto est doloribus.",
                            Image = "http://lorempixel.com/640/480/cats",
                            Price = 12f,
                            Title = "est"
                        },
                        new
                        {
                            Id = 24,
                            Description = "Sapiente et at odit totam atque recusandae provident beatae. Odio reprehenderit id et et. Eos sint ut. Aperiam est molestiae cupiditate et nobis sunt sapiente velit. Consequuntur et quo corporis consequatur. Commodi rerum porro totam dignissimos amet fuga.",
                            Image = "http://lorempixel.com/640/480/cats",
                            Price = 79f,
                            Title = "doloribus"
                        },
                        new
                        {
                            Id = 25,
                            Description = "Dolor accusamus sequi odit quisquam aut omnis ut itaque voluptas. Dolor qui ut sit. Neque quidem soluta corporis dolores quaerat possimus magnam velit.",
                            Image = "http://lorempixel.com/640/480/sports",
                            Price = 38f,
                            Title = "eveniet"
                        },
                        new
                        {
                            Id = 26,
                            Description = "Voluptas ut id sequi dolor sit aut sit. Id cupiditate assumenda. Eaque facilis itaque architecto rem vero vel explicabo.",
                            Image = "http://lorempixel.com/640/480/animals",
                            Price = 29f,
                            Title = "pariatur"
                        },
                        new
                        {
                            Id = 27,
                            Description = "Fugit ut et molestiae quibusdam non dolores. Natus enim dolor et autem. Optio qui natus. Dolor est mollitia.",
                            Image = "http://lorempixel.com/640/480/nature",
                            Price = 65f,
                            Title = "dolor"
                        },
                        new
                        {
                            Id = 28,
                            Description = "Asperiores quis in facilis facere qui quo expedita numquam. Fugit sequi consequatur deserunt. Qui voluptatum autem possimus eum soluta at fugit. Natus eos alias porro non qui exercitationem facilis sed a. Pariatur eligendi repudiandae sint ex non dolores repellendus quos doloremque.",
                            Image = "http://lorempixel.com/640/480/food",
                            Price = 34f,
                            Title = "voluptatem"
                        },
                        new
                        {
                            Id = 29,
                            Description = "Et ut quas saepe. Eos ipsum et vitae. Qui repellat qui qui repudiandae totam tenetur.",
                            Image = "http://lorempixel.com/640/480/technics",
                            Price = 69f,
                            Title = "amet"
                        },
                        new
                        {
                            Id = 30,
                            Description = "Vero ea ullam unde quasi fuga sint. Accusamus vel fuga qui. Veritatis eos nemo quibusdam. Cum veritatis eum ut provident provident ea delectus culpa. Qui esse non corporis quos soluta autem.",
                            Image = "http://lorempixel.com/640/480/animals",
                            Price = 64f,
                            Title = "repellendus"
                        },
                        new
                        {
                            Id = 31,
                            Description = "Quo molestiae maxime aut quis repellat libero. Sit est illo vero odit facilis minus a accusamus. Qui odit quae ex impedit qui veniam quia labore.",
                            Image = "http://lorempixel.com/640/480/nightlife",
                            Price = 72f,
                            Title = "est"
                        },
                        new
                        {
                            Id = 32,
                            Description = "Minus dolores aliquid et. Cupiditate nesciunt voluptate ullam. Incidunt aut commodi tempore adipisci nulla hic quam. Dolorem totam sapiente et. Eius exercitationem est ab omnis.",
                            Image = "http://lorempixel.com/640/480/business",
                            Price = 24f,
                            Title = "eaque"
                        },
                        new
                        {
                            Id = 33,
                            Description = "Quia aut exercitationem dolorem et ut laborum id consequatur. Quia ut dicta laborum consequuntur. Occaecati enim consequatur aut quisquam assumenda. Asperiores nobis eos quibusdam odit facilis aspernatur error. Accusamus et omnis eius omnis quia et aut numquam qui. Sit incidunt ipsam quia.",
                            Image = "http://lorempixel.com/640/480/animals",
                            Price = 94f,
                            Title = "nostrum"
                        },
                        new
                        {
                            Id = 34,
                            Description = "Atque illo qui aliquid laboriosam ullam qui earum unde quas. Impedit facere sit. Officia inventore et. Qui et molestiae libero asperiores et qui omnis quis. Nobis dolor ad quam tempore blanditiis vel ex.",
                            Image = "http://lorempixel.com/640/480/business",
                            Price = 90f,
                            Title = "consequatur"
                        },
                        new
                        {
                            Id = 35,
                            Description = "Suscipit impedit rerum ducimus molestiae quae minima dolorum. Voluptatem provident veniam. Iste eum voluptatem id. Ut est nostrum eos voluptas vel quis vitae qui modi. Eos accusantium qui velit. Deserunt a aliquid dolorem accusantium quo sunt aperiam et nesciunt.",
                            Image = "http://lorempixel.com/640/480/nature",
                            Price = 22f,
                            Title = "aliquam"
                        },
                        new
                        {
                            Id = 36,
                            Description = "Quia laudantium doloribus porro non eum. Eum dolorem neque ut voluptatem inventore. Adipisci asperiores rerum officiis quaerat delectus. Quibusdam similique et dolorem soluta aliquam. Dolorem quasi ratione est. Autem accusantium in aperiam accusamus velit mollitia sed in.",
                            Image = "http://lorempixel.com/640/480/nightlife",
                            Price = 10f,
                            Title = "et"
                        },
                        new
                        {
                            Id = 37,
                            Description = "Est iusto neque. Voluptatem ipsum itaque alias voluptate saepe consequuntur necessitatibus non. Labore numquam facere perferendis. Dolores ut ea quibusdam sapiente beatae tempore distinctio.",
                            Image = "http://lorempixel.com/640/480/sports",
                            Price = 87f,
                            Title = "cum"
                        },
                        new
                        {
                            Id = 38,
                            Description = "Et et est quibusdam. Enim aut voluptatum. Temporibus et molestias et reiciendis libero totam aut ea omnis. Reiciendis eveniet voluptas quis rerum sed quisquam deserunt excepturi sunt. Eos voluptas earum praesentium.",
                            Image = "http://lorempixel.com/640/480/technics",
                            Price = 57f,
                            Title = "ut"
                        },
                        new
                        {
                            Id = 39,
                            Description = "Magni modi id voluptatum quod nostrum. Aspernatur consequatur consectetur. Corrupti quos sunt quia provident rerum quia sequi et unde.",
                            Image = "http://lorempixel.com/640/480/cats",
                            Price = 97f,
                            Title = "dignissimos"
                        },
                        new
                        {
                            Id = 40,
                            Description = "Dolor delectus occaecati temporibus hic iusto. Nostrum eos possimus exercitationem. Perspiciatis aliquid voluptatem fuga officia. Consequuntur distinctio est possimus minus. Doloribus adipisci quis voluptate recusandae quo aliquam aut fugiat ut.",
                            Image = "http://lorempixel.com/640/480/animals",
                            Price = 17f,
                            Title = "et"
                        },
                        new
                        {
                            Id = 41,
                            Description = "Non laboriosam sed quo. Labore animi dolor aut et molestiae. Facilis tempore reiciendis eum nihil ut deserunt et.",
                            Image = "http://lorempixel.com/640/480/nature",
                            Price = 23f,
                            Title = "culpa"
                        },
                        new
                        {
                            Id = 42,
                            Description = "Et quos qui. Labore et ipsa autem beatae. Quia ducimus ipsa minima est reprehenderit esse. Facere aut dolores est magni vero.",
                            Image = "http://lorempixel.com/640/480/food",
                            Price = 72f,
                            Title = "maxime"
                        },
                        new
                        {
                            Id = 43,
                            Description = "Corrupti vel deserunt nulla est hic. Ratione quas error officia aut sit similique architecto. Eum vel a ut voluptate laboriosam nam doloribus. Necessitatibus saepe commodi mollitia voluptas. Numquam inventore a deserunt eius minus id. Sit rerum dolore repudiandae et.",
                            Image = "http://lorempixel.com/640/480/business",
                            Price = 21f,
                            Title = "pariatur"
                        },
                        new
                        {
                            Id = 44,
                            Description = "Velit ab nemo. Vitae consequatur ratione quo animi dolores et inventore eum unde. Perferendis quis dolorem quis aut at molestiae dolor.",
                            Image = "http://lorempixel.com/640/480/abstract",
                            Price = 67f,
                            Title = "aut"
                        },
                        new
                        {
                            Id = 45,
                            Description = "Maxime dolorem modi dicta pariatur nemo. Temporibus et quia aut hic dignissimos. Magni aut omnis enim natus cumque aliquam.",
                            Image = "http://lorempixel.com/640/480/technics",
                            Price = 82f,
                            Title = "a"
                        },
                        new
                        {
                            Id = 46,
                            Description = "Velit ad enim. Ut quia pariatur quisquam ut. Enim porro quia architecto voluptatem accusamus assumenda ab pariatur. Non aliquid autem libero rem ex.",
                            Image = "http://lorempixel.com/640/480/food",
                            Price = 51f,
                            Title = "ullam"
                        },
                        new
                        {
                            Id = 47,
                            Description = "Et et dolor. Quia occaecati a. Pariatur aut est. Ex quo quo veritatis atque omnis eum. Maxime ducimus perferendis sed. Deleniti animi vel voluptates est reprehenderit unde dolores maxime.",
                            Image = "http://lorempixel.com/640/480/city",
                            Price = 15f,
                            Title = "ipsum"
                        },
                        new
                        {
                            Id = 48,
                            Description = "Aliquid vel doloribus. Voluptatem aut illum. Eum harum nostrum repudiandae et temporibus. Veniam rem quidem et quaerat rerum sint ratione. Consequuntur impedit quia in. Quos est quidem sint cupiditate aperiam voluptas.",
                            Image = "http://lorempixel.com/640/480/nature",
                            Price = 50f,
                            Title = "molestiae"
                        },
                        new
                        {
                            Id = 49,
                            Description = "Ipsa assumenda dolor. Consequatur atque omnis iusto laudantium officiis molestiae. Quo iure iusto libero. Officiis est harum esse eum laboriosam eos expedita in. Facere autem non accusantium earum excepturi.",
                            Image = "http://lorempixel.com/640/480/business",
                            Price = 64f,
                            Title = "optio"
                        },
                        new
                        {
                            Id = 50,
                            Description = "Ipsam tempora velit delectus qui et ut. Aut dolores animi expedita repudiandae sunt. Aut et non. Voluptatem sapiente velit aspernatur consequatur veritatis. Pariatur atque libero atque autem nostrum cumque enim natus vel. Qui est quisquam sint.",
                            Image = "http://lorempixel.com/640/480/business",
                            Price = 64f,
                            Title = "ratione"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
